Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:me-south-1:692889134364:task-definition/Receipts-task1-Deploy:12"
        LoadBalancerInfo:
          ContainerName: "Receipts-Container1-Deploy"
          ContainerPort: 80
# Optional properties



# files:
#  - source: /node-backend
#    destination: /var/www/receipts
#hooks:
 # BeforeInstall:
 #   - location: deploy_scripts/before_install.sh
 #     timeout: 300
 #     runas: root
 # AfterInstall:
 #   - location: deploy_scripts/after_install.sh
 #     timeout: 300
 #     runas: root
 # ApplicationStart:
 #   - location: deploy_scripts/start_server.sh
 #     timeout: 300
 #     runas: root
 # ApplicationStop:
 #   - location: deploy_scripts/stop_server.sh
 #     timeout: 300
 #     runas: root
#        PlatformVersion: "[Version number, ex: 1.3.0]"
#        NetworkConfiguration:
#          AwsvpcConfiguration:
#            Subnets: ["SubnetId1","SubnetId2"]
#            SecurityGroups: ["ecs-security-group-1"]
#            AssignPublicIp: "ENABLED-or-DISABLED"
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-ecs
#Hooks:
#  
#  
#  
#  
#  
